//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwittsExchange.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tweet
    {
        public System.Guid Id { get; set; }
        public string Author { get; set; }
        public string Text { get; set; }
        public string Media { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
